spring:
  application:
    name: blog-app-api

  datasource:
    url: jdbc:postgresql://localhost:5432/mytest
    username: employeecoreapirole
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml